# Generated by Django 3.0.4 on 2020-03-16 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=512)),
                ('checked_by_moderator', models.BooleanField(default=False)),
                ('created_by', models.PositiveIntegerField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('deleted_flg', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now_add=True)),
                ('deleted_flg', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Places.Place')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.PositiveIntegerField()),
                ('pic_link', models.URLField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('deleted_flg', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Places.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Accept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.PositiveIntegerField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('deleted_flg', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepts', to='Places.Place')),
            ],
        ),
    ]
