# Generated by Django 3.0.4 on 2020-04-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0002_auto_20200316_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeimage',
            name='pic_link',
        ),
        migrations.AddField(
            model_name='placeimage',
            name='pic_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
