# Generated by Django 3.0.4 on 2020-05-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0003_auto_20200410_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='checked_by_moderator',
        ),
    ]
