# Generated by Django 3.0.4 on 2020-05-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0004_remove_place_checked_by_moderator'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(check=models.Q(('latitude__gte', 55.515174), ('latitude__lte', 56.106229)), name='lat_msk_constraint'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.CheckConstraint(check=models.Q(('longitude__gte', 36.994695), ('longitude__lte', 37.956703)), name='long_msk_constraint'),
        ),
    ]
